---
- name: Install HTTPD servers
  hosts: group1
  become: yes

  tasks:
    - name: Install HTTPD
      yum:  
        name: httpd
        state: present
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Redhat"  

    - name: Start httpd Service
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Redhat"  