---
- name: Websites is under maintenance
  hosts: ansible2Cent
  become: yes

  tasks:
    - name: Update Maintenance
      copy:  
        src: Maintenance.html
        dest: /var/www/html/index.html

...
        