---
- name: Install HTTPD On Ubuntu servers
  hosts: ansible1CentOS
  become: yes

  tasks:
    - name: Install apache2
      yum:  
        name: apache2
        state: present

    - name: Start apache Service
      service:
        name: apache2
        state: started
        enabled: yes

        