---
- name: Install HTTPD On Ubuntu servers
  hosts: group1
  become: yes

  tasks:
    - name: Install apache2
      yum:  
        name: apache2
        state: present
      when: ansible_distrubution == "Amozon"

    - name: Start apache2 Service
      service:
        name: apache2
        enabled: yes
      when: ansible_distrubution == "Amozon"  

    - name: Enable apache2 Service
      service:
        name: apache2
        state: 
        enabled: yes    
      when: ansible_distrubution == "Amozon"  

  tasks:
    - name: Install apache2
      apt:  
        name: apache2
        state: present
      when: ansible_distrubution == "Ubuntu"  

    - name: Start apache Service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distrubution == "Ubuntu"  

    - name: Enable apache2 Service
      service:
        name: apache2
        enabled: yes    
      when: ansible_distrubution == "Ubuntu"    
...     